# Generated by Django 4.1.5 on 2023-03-02 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproject',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='价值必须大于0.01')], verbose_name='目的捐赠价值'),
        ),
        migrations.AlterField(
            model_name='donationproject',
            name='get_donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='当前筹集金额'),
        ),
    ]
