# Generated by Django 4.1.5 on 2023-03-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donationproject_donation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to='donation.donationproject', verbose_name='所属捐赠项目'),
        ),
    ]
