# Generated by Django 4.1.5 on 2023-03-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_news_project'),
        ('donation', '0003_alter_donationrecord_donation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproject',
            name='project_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='news.news', verbose_name='捐赠新闻'),
        ),
    ]
