# Generated by Django 4.1.5 on 2023-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donationproject_project_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproject',
            name='project_status',
            field=models.CharField(choices=[('0', '编辑'), ('1', '发起'), ('2', '完成'), ('3', '截止')], max_length=10, verbose_name='项目状态'),
        ),
    ]
