# Generated by Django 4.1.5 on 2023-03-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donationproject_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationrecord',
            options={'ordering': ['donation_user', '-donation_amount'], 'verbose_name': '捐赠记录', 'verbose_name_plural': '捐赠记录'},
        ),
    ]
