# Generated by Django 4.1.5 on 2023-03-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_remove_donationrecord_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationproject',
            options={'ordering': ['-start_time'], 'verbose_name': '捐赠项目', 'verbose_name_plural': '捐赠项目'},
        ),
    ]
