# Generated by Django 4.1.5 on 2023-05-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_client_alter_donationproject_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
