# Generated by Django 4.1.5 on 2023-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='委托人姓名')),
                ('contact', models.CharField(max_length=20, verbose_name='委托人联系方式')),
                ('address', models.CharField(max_length=100, verbose_name='委托人地址')),
                ('is_organization', models.BooleanField(default=False, verbose_name='是否为慈善机构')),
                ('organization_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='机构名称')),
            ],
        ),
    ]
