# Generated by Django 4.1.5 on 2023-05-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0012_client_proof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': '委托人', 'verbose_name_plural': '委托人'},
        ),
        migrations.AddField(
            model_name='donationproject',
            name='project_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='donation.client', verbose_name='项目委托人'),
        ),
    ]
