# Generated by Django 4.1.5 on 2023-05-14 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_alter_client_options_donationproject_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='proof',
            field=models.FileField(upload_to='donor_proofs', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='证明文件'),
        ),
    ]
