# Generated by Django 4.1.5 on 2023-03-02 02:40

import apps.item.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='物品名称')),
                ('detail', models.CharField(max_length=100, verbose_name='物品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='单价必须大于0')], verbose_name='物品价格')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='数量必须大于1')], verbose_name='物品数量')),
                ('item_iamge', models.ImageField(blank=True, null=True, upload_to=apps.item.models.DonationItem.itemImage_directory_path, verbose_name='物品照片')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_items', to='item.category', verbose_name='物品类别')),
                ('donation_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_items', to='donation.donationproject', verbose_name='所属捐赠项目')),
                ('donation_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donationrecord', verbose_name='所属捐赠记录')),
            ],
            options={
                'verbose_name': '捐赠物资',
                'verbose_name_plural': '捐赠物资',
            },
        ),
    ]
