# Generated by Django 4.1.5 on 2023-03-02 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
        ('item', '0002_donationitem_requestitem_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='donation_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='donation.donationproject', verbose_name='所属捐赠项目'),
        ),
    ]
