# Generated by Django 4.1.5 on 2023-03-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donationproject_donation_amount_and_more'),
        ('item', '0004_donationitem_all_price_requestitem_all_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitem',
            name='donation_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_items', to='donation.donationrecord', verbose_name='所属捐赠记录'),
        ),
    ]
