# Generated by Django 4.1.5 on 2023-03-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_donationitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationitem',
            old_name='item_iamge',
            new_name='item_image',
        ),
    ]
