# Generated by Django 4.1.5 on 2023-05-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_donationitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='物品类型'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='物品slug'),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '待审核'), ('1', '暂存'), ('2', '捐赠完成')], default='0', max_length=10, verbose_name='状态'),
        ),
    ]
