# Generated by Django 4.1.5 on 2023-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationitem',
            name='love_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='爱心寄语'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='storage_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='存储位置'),
        ),
    ]
