# Generated by Django 4.1.5 on 2023-05-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_donationitem_love_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Require',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='要求名称')),
                ('information', models.TextField(max_length=500, verbose_name='要求信息')),
                ('request_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='item.requestitem', verbose_name='请求的物品')),
            ],
            options={
                'verbose_name': '物资要求',
                'verbose_name_plural': '物资要求',
                'ordering': ['name'],
            },
        ),
    ]
