# Generated by Django 4.1.5 on 2023-05-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_require'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='require',
            options={'verbose_name': '物资要求', 'verbose_name_plural': '物资要求'},
        ),
        migrations.AlterField(
            model_name='require',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='item.requestitem', verbose_name='请求的物品'),
        ),
    ]
