# Generated by Django 4.1.5 on 2023-05-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_alter_require_options_alter_require_request_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='require',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='item.requestitem', verbose_name='请求的物品'),
        ),
    ]
