# Generated by Django 4.1.5 on 2023-03-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_news_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_project',
        ),
    ]
