# Generated by Django 4.1.5 on 2023-03-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_news_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_time'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('0', '编辑'), ('1', '发布')], default=0, max_length=5, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
