# Generated by Django 4.1.5 on 2023-03-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_announcement_author_announcement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_time'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
    ]
