# Generated by Django 4.1.5 on 2023-05-15 16:04

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
