# Generated by Django 4.1.5 on 2023-05-15 17:20

import apps.news.models
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='markdown正文'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=apps.news.models.News.newsImage_directory_path, verbose_name='新闻封面'),
        ),
    ]
