# Generated by Django 4.1.5 on 2023-05-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_body_alter_news_content_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='markdown_body',
        ),
    ]
