# Generated by Django 4.1.5 on 2023-03-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='user.donationproject', verbose_name='所属捐赠项目'),
        ),
    ]
