# Generated by Django 4.1.5 on 2023-03-01 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_donationrecord_donation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationproject',
            name='project_status',
            field=models.CharField(choices=[(0, '创建'), (1, '发起'), (2, '完成'), (3, '截止')], default=0, max_length=10, verbose_name='项目状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationproject',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='目的捐赠价值'),
        ),
        migrations.AlterField(
            model_name='donationproject',
            name='get_donation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前筹集金额'),
        ),
        migrations.AlterField(
            model_name='donationproject',
            name='item_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='数量必须大于1')], verbose_name='物品数量'),
        ),
        migrations.AlterField(
            model_name='donationproject',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='单价必须大于1')], verbose_name='物品单价'),
        ),
    ]
