# Generated by Django 4.1.5 on 2023-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_donationproject_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationproject',
            name='project_status',
            field=models.CharField(choices=[('0', '创建'), ('1', '发起'), ('2', '完成'), ('3', '截止')], max_length=10, verbose_name='项目状态'),
        ),
    ]
