# Generated by Django 4.1.5 on 2023-03-01 10:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_donationproject_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationrecord',
            options={'verbose_name': '捐赠记录', 'verbose_name_plural': '捐赠记录'},
        ),
        migrations.AddField(
            model_name='donationitem',
            name='quantity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, message='数量必须大于1')], verbose_name='物品数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='item_iamge',
            field=models.ImageField(blank=True, null=True, upload_to='item_iamge', verbose_name='物品照片'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='捐赠价值'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to=settings.AUTH_USER_MODEL, verbose_name='捐赠者'),
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='status',
            field=models.CharField(choices=[('0', '审核'), ('1', '暂存'), ('2', '完成')], max_length=10, verbose_name='捐赠状态'),
        ),
    ]
