# Generated by Django 4.1.5 on 2023-03-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_donationrecord_options_donationitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donationitem',
            name='donation_project',
        ),
        migrations.RemoveField(
            model_name='donationitem',
            name='donation_record',
        ),
        migrations.RemoveField(
            model_name='donationproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='donation_project',
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='donation_user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DonationItem',
        ),
        migrations.DeleteModel(
            name='DonationProject',
        ),
        migrations.DeleteModel(
            name='DonationRecord',
        ),
    ]
