# Generated by Django 4.1.5 on 2023-03-07 07:43

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_donationitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.MyUser.userAvatars_directory_path, verbose_name='头像'),
        ),
    ]
